[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.build]
cmds = ["npm install", "npm run build", "cp -r .next/static .next/standalone/.next/static", "cp -r public .next/standalone/public || true"]

[start]
cmd = "node .next/standalone/server.js"
